export interface Icategories {
}

// Generated by https://quicktype.io

export interface Icategories {
  _id:       string;
  name:      string;
  slug:      string;
  image:     string;
  createdAt: Date;
  updatedAt: Date;
}

